Refactored the storage adapter tests to use a `beforeEach` hook
automerge/automerge-repo pull request #385
Opened 2024-09-06 12:37 UTC by kraenhansen

To implement tests of a storage which use async APIs, I need the `teardown` function to be able to return a promise which gets awaited. I also took the liberty to refactor the tests a bit to use a `beforeEach` hook instead of calling `setup` and `teardown` in each of the tests. This ensures the `teardown` gets called even if the test fails. In the current state, this isn't the case since something throwing in the test could prevent the call to `teardown`.

2024-09-06 12:41 UTC, kraenhansen commented
cc @HerbCaudill as it seems you've worked on this file too 👍

2024-09-20 13:04 UTC, HerbCaudill requested changes

2024-09-20 13:04 UTC, HerbCaudill commented on packages/automerge-repo/src/helpers/tests/storage-adapter-tests.ts
> +const it = test<AdapterTestContext>
small nitpick - I'd prefer 
```ts
import { ..., it as _it } from "vitest"

...

const it = _it<AdapterTestContext>
```

2024-09-20 13:04 UTC, HerbCaudill commented
Hi @kraenhansen. Thanks for working on this, and for introducing me to Vitest's test context API! I've leaned heavily on the `setup()` pattern to avoid `beforeEach` + global mutable state, but this is much cleaner. 

(For anyone following along, it took me a while to find this in the docs - it's not referenced in the [API reference](https://vitest.dev/api/#beforeeach), but it's documented in a standalone guide to [Test Context](https://vitest.dev/guide/test-context.html#beforeeach-and-aftereach).)

2024-09-21 13:10 UTC, kraenhansen commented on packages/automerge-repo/src/helpers/tests/storage-adapter-tests.ts
> +const it = test<AdapterTestContext>
Done 👍

2024-09-21 13:23 UTC, HerbCaudill approved these changes

2024-09-21 13:23 UTC, merged